config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_entity
    end
  end

  def destroy

    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to lists_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmark new</h1>


<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <p class="navbar-brand"><%= link_to 'My lists', lists_path, class: "text-decoration-none link-dark" %></p>
      <%# <a class="navbar-brand" href="../lists/index"><i class="fa-solid fa-clapperboard"></i> My lists</a> %>
      <a class="navbar-brand" href="../lists/new">New list</a>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class= "banner">
  <h1>Movies</h1>
</div>

<div class= "container">
<% @lists.each do |list| %>
<div class="card">
    <h2><%= link_to list.name, list %></h2>

</div>
<% end %>
</div>

app/views/lists/new.html.erb
<h1>List new</h1>

<%= render "form", list: @list %>

<%= link_to "Back", lists_path %>

app/views/lists/show.html.erb
<div class="listbanner">
<h1><%= @list.name %></h1>
</div>

<div class="button">
<%= link_to 'New movie', new_list_bookmark_path(params[:id]), class: "btn btn-info"  %>
</div>

<div class="listcontainer">
<% @list.bookmarks.each do |bookmark|%>
  <div class="listcard">
    <p><%= image_tag (bookmark.movie.poster_url), alt: "Le Wagon",  class: "image" %></p>
    <div class="titre d-flex justify-content-start mx-2">
      <p><%= bookmark.movie.title %></p>
      <p><%= bookmark.movie.rating %></p>
      <i class="fa-solid fa-star"></i>
    </div>
    <p><%= bookmark.movie.overview %></p>
    <div class="d-flex justify-content-between mx-2">
      <p><i class="fa-solid fa-quote-right"></i><%= bookmark.comment %></p>
      <%= link_to 'delete', bookmark_path(bookmark) , data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </div>
  </div>
<% end %>
</div>